name: anamoly detector
language: Python
variables:
  - name: input
    inputType: InputTopic
    defaultValue: stocks
  - name: output
    inputType: OutputTopic
    defaultValue: anamolies
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: starter-transformation
